/*
 * This Java source file was generated by the Gradle 'init' task.
 * template from https://docs.oracle.com/javase/8/javafx/get-started-tutorial/hello_world.htm
 */
package modder;

import picocli.CommandLine;

//
public class App {
    public static void cliInit(String[] args) {
        CommandLine cli = new CommandLine(new ModderMainCmd());

        // ========== set some options =============
        // https://picocli.info/
        // allow case insensitive
        cli.setSubcommandsCaseInsensitive(true);
        cli.setOptionsCaseInsensitive(true);
        // allow abbreviations
        cli.setAbbreviatedOptionsAllowed(true);
        cli.setAbbreviatedSubcommandsAllowed(true);
        // execute
        int exitCode = cli.execute(args);
        System.exit(exitCode);

    }

    public static void main(String[] args) {
        // Some testing
        if (Util.DoesCommandExist("adb")) {
            System.out.println("adb exist");
        } else {
            System.out.println("adb doesn't exist");

        }
        cliInit(args);

    }
}
