/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package modder;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class TestUtil {
    @Test
    void DoesCommandExist() {
        // commands that should exit on windows and unix like OS
        assertEquals(true, Util.DoesCommandExist("ping"));
        assertEquals(true, Util.DoesCommandExist("echo"));
        // some random command that will never exist
        assertEquals(false, Util.DoesCommandExist("wioiofj902jnci43b199u"));
        assertEquals(false, Util.DoesCommandExist("u3902u9hbrnodooej2hwioehfwejof"));
        assertEquals(false, Util.DoesCommandExist("3490t433ocworo3i40ehfh"));
        assertEquals(false, Util.DoesCommandExist("93u09u904utoidwwht4j39"));
    }
}
